# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161009_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.TimeField()),
                ('description', models.TextField()),
                ('slots', models.IntegerField()),
                ('speaker', models.ManyToManyField(to='core.Speaker')),
            ],
        ),
    ]
